[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "cd app && npm run start"
  healthcheckPath = "/api/health"
  healthcheckTimeout = 30

[[services]]
  name = "web"

[build.env]
  NODE_ENV = "production"
